name: Hello CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Verifier la version de Node
        run: node -v    
      - name: Dire bonjour
        run: echo "Hello CI depuis le runner"
      - name: Inspecter le dossier
        run: ls -la